### ISSUE TITLE
Port number not guaranteed to be numeric

### ISSUE THREAD

**Issue by cwatsonc** [jelhub/scimgateway#10]
On cloud systems and especially MS Azure the network abstractions sometimes take alternate forms.  Within Azure ports are identified as "named pipes" which may take a form other than numeric.

In the `isValidconfig` function checks for a numeric value:

`else if (key === 'port') { // number`
`           //on PaaS sometimes the port is delivered as non-numeric string`
`           //if (!val || typeof (val) !== 'number') return false;`
`       }`

This needed to be commented out in order to run the solution on MS Azure.  Since the plugin-xxxx.json config is tightly coupled with the plugin-xxxx.js modules would it make sense to move the validation to the plugin-xxxx.js?

In that fashion users can provide their own solution for the validation step that matches their context.

**Comment by jelhub** [comment]
New version 0.4.5 do not use "isValidconfig" and will not validate port settings.

Port number may now also be overridden by setting environment variables before starting the gateway. Setting the ScimGateway port in the configuartion file to "process.env.XXX" where XXX is the environment variable let gateway use environment variable for port configuration. This could be useful in cloud systems e.g:

  "scimgateway": {
      ...
      "port": "process.env.PORT",
      ...
  }

**Comment by cwatsonc** [comment]
Verified working in 0.4.5
