### ISSUE TITLE
How to change ServiceProviderConfig

### ISSUE THREAD

**Issue by christinedraper** [jelhub/scimgateway#101]
Is there a way to change what is returned by `/ServiceProviderConfig` or to disable the endpoint? In the standard its an optional endpoint but I would want it to be accurate if I expose it.  It looks like it is hardcoded to specific values, and for example if I'm supporting only http Bearer auth and not supporting changePassword I can't communicate that.

**Comment by jelhub** [comment]
v4.2.12 update: 

- Schemas, ServiceProviderConfig and ResourceType can be customized if `lib/scimdef-v2.js (or scimdef-v1.js)` exists. Original scimdef-v2.js/scimdef-v1.js can be copied from node_modules/scimgateway/lib to your plugin/lib and customized.

**Comment by christinedraper** [comment]
Thank you yet again!
