### ISSUE TITLE
How to limit the attributes in default schema?

### ISSUE THREAD

**Issue by infinitetrooper** [jelhub/scimgateway#102]
Hi, we're trying to limit the attributes sent to AD when Provisioning is configured. It currently sends all the attributes in the list `lib/scimdef-v2.js` but, we only need 4 (userName, displayName, id, and active). 

Is there any way we can make those 4 attributes the default schema for our integration so that users don't need to delete the unnecessary attributes when setting up provisioning?

Thanks in advance.

**Comment by jelhub** [comment]
Hi,
Schemas can be customized in v4.2.12
Please see release notes:

### v4.2.12  

[Added] 

- Schemas, ServiceProviderConfig and ResourceType can be customized if `lib/scimdef-v2.js (or scimdef-v1.js)` exists. Original scimdef-v2.js/scimdef-v1.js can be copied from node_modules/scimgateway/lib to your plugin/lib and customized.

**Comment by infinitetrooper** [comment]
Thanks!
