### ISSUE TITLE
Configurable path for plugin-config.json

### ISSUE THREAD

**Issue by dbollaer** [jelhub/scimgateway#109]
Hello,

I want to separate my config from the rest of my project.
For automatisation reasons, it's a bit annoying that the plugin-config.json file needs to inside the project.

Ideally I would be able to change this file and file path, to be outside my project.

Could you please let me know, if this would be possible?

Thank you in advance.

**Comment by jelhub** [comment]
Hi,

Please see: https://github.com/jelhub/scimgateway?tab=readme-ov-file#configuration-notes

There are 3 options:
- using environments: `process.env.<ENVIRONMENT>`
- using external file: `process.file.<path>`
- individual secret text: `process.text.<path>`

Also, they can be mixed

Regards,
Jarle

**Comment by dbollaer** [comment]
Thank you I understand now!
