### ISSUE TITLE
Just a suggestion.  How to run a new scimgateway project as a docker container.

### ISSUE THREAD

**Issue by visualjeff** [jelhub/scimgateway#11]
Instructions for running a new scimgateway project as a docker container.  This includes a solution for file system persistence (for the plugin configs and loki.db) between container restarts:

**Documentation / How to:**

[https://gist.github.com/visualjeff/796f9b49d1b3ec633f794df719e6e1c6#file-gistfile1-txt](https://gist.github.com/visualjeff/796f9b49d1b3ec633f794df719e6e1c6#file-gistfile1-txt)

**Three files need to be added to a new scimgateway project to dockerize it:**

1. docker-compose.yml

[https://gist.githubusercontent.com/visualjeff/796f9b49d1b3ec633f794df719e6e1c6/raw/88483166411d7df6d791a7a3a20fccc038b3aad6/docker-compose.yml](https://gist.githubusercontent.com/visualjeff/796f9b49d1b3ec633f794df719e6e1c6/raw/88483166411d7df6d791a7a3a20fccc038b3aad6/docker-compose.yml)

2. Dockerfile

[https://gist.githubusercontent.com/visualjeff/796f9b49d1b3ec633f794df719e6e1c6/raw/88483166411d7df6d791a7a3a20fccc038b3aad6/Dockerfile](https://gist.githubusercontent.com/visualjeff/796f9b49d1b3ec633f794df719e6e1c6/raw/88483166411d7df6d791a7a3a20fccc038b3aad6/Dockerfile)

3. DataDockerfile

[https://gist.githubusercontent.com/visualjeff/796f9b49d1b3ec633f794df719e6e1c6/raw/88483166411d7df6d791a7a3a20fccc038b3aad6/DataDockerfile](https://gist.githubusercontent.com/visualjeff/796f9b49d1b3ec633f794df719e6e1c6/raw/88483166411d7df6d791a7a3a20fccc038b3aad6/DataDockerfile)

Jeff

**Comment by jelhub** [comment]
Hi,

Thanks a lot for sharing your work.
This was great, successfully tested on Ubuntu Trusty (14.04)

What would be the best approach for including it to ScimGateway?

Suggest having:

> ./docker-compose.yml (modified dockerfile path)
> ./config/docker/Dockerfile
> ./config/docker/DataDockerfile

> Readme contains howto

If you don't mind, I would like to add you to the collaborators list and you will have push access to repository


Regards,
Jarle

**Comment by visualjeff** [comment]
Thanks Jarle!  I like your suggestion.  Seems straight forward and simple.

Currently I’m at Dockercon 2017 in Austin, TX  (with Charley Watson).  But when I get back to Seattle I’ll carefully work my changes in.  

Jeff

**Comment by jelhub** [comment]
Hi,
Your dockerization suggestion have now been included in v0.4.6
I've also sent you a collaborator invite and you will have push access to repo

Thanks,
Jarle
