### ISSUE TITLE
Override base URL for metadata.location

### ISSUE THREAD

**Issue by christinedraper** [jelhub/scimgateway#110]
Is there any way to override the base URL for location in the response metadata?  Our scim service is running in a k8s cluster behind a proxy, so the location should be  the external endpoint (base URL + path). What we're getting is the internal service URL.

**Comment by christinedraper** [comment]
The main concern is not exposing internal host info. Its reassuring that you're not aware of IDPs using the information. Either of the approaches you suggest would work for us, the first would be simpler to set up.

**Comment by jelhub** [comment]
Now fixed.
Ref:

## Change log  

### v4.4.4  

[Added]

- New configuration: **scim.skipMetaLocation**  
 true or false, default false. If set to true, `meta.location` which contains protocol and hostname from request-url, will be excluded from response e.g. `"{...,meta":{"location":"https://my-company.com/<...>"}}`. If using reverse proxy and not including headers `X-Forwarded-Proto` and `X-Forwarded-Host`, originator will be the proxy and we might not want to expose internal protocol and hostname being used by the proxy request.

Below is an example of nginx reverse proxy configuration supporting SCIM Gateway ipAllowList and correct meta.location response:  

	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Forwarded-Host $http_host;
