### ISSUE TITLE
Support for PATCH with replace used on an array to set it to empty

### ISSUE THREAD

**Issue by christinedraper** [jelhub/scimgateway#111]
Okta and PingIdentity use a PATCH group to set the members to an empty array.  I think the gateway is interpreting this as a replace of the data of an empty list of memberships, but the provisioners are intending to delete all the members.

The request Okta is sending is:
```
PATCH {{basePath}}/Groups/org-cd-1:admin
Content-Type: application/json
Authorization: {{authz}}

{
    "Operations":[{"op":"replace","value":{"id":"org-cd1:admin","displayName":"org-cd1:admin", "members":  []}}]
}

```

Re PingIdentity see:
https://support.pingidentity.com/s/question/0D58Z000090xPI4SAM/why-patch-group-request-uses-replace-operation-with-empty-value-when-removing-all-members-of-the-group

which uses the `path` syntax but is similar to above.

**Comment by jelhub** [comment]
Now fixed in v4.4.5
Thanks, Jarle
