### ISSUE TITLE
When Microsoft Entra ID sends a delete request, SCIM isn't handling it properly.

### ISSUE THREAD

**Issue by inchandru** [jelhub/scimgateway#122]
Hi Guys,

When users are permanently deleted in Microsoft Entra ID, a delete request is sent to SCIM. However, it seems that SCIM is not handling delete request properly, it throws an error of **invalid attribute type name**. 

I'm using LDAP as an backend.

Logs:

<img width="1727" alt="image" src="https://github.com/jelhub/scimgateway/assets/55099628/dc1c66cc-ce6b-4849-92ef-494344dfbf97">

Your help is appreciated, Thank you in advance.

**Comment by jelhub** [comment]
Now fixed in v4.5.4

**Comment by inchandru** [comment]
Hai @jelhub 

Thank you for the fix, it's working now
