### ISSUE TITLE
Entra keep on sending the patch request while using the customised attribute

### ISSUE THREAD

**Issue by niranjanvk** [jelhub/scimgateway#124]
Hi,

I am using the custom extension "urn:ietf:params:scim:schemas:extension:CustomExtensionName:2.0:User.otherMails" (type array and inboundtype string) for attribute otherMails and even after creating the otherMails using scimgateway's plugin-ldap in ldap, entra keep on sending the patch request. The repetitive patch request is because the outbound response of the Get search request by ID does not have proper attribute name.

Sample outbound-

{"statusCode":200,"statusMessage":"OK","body":{"id":"<sample_id>","userName":"<sample_userName>","name":{"familyName":"test1"},"urn:ietf:params:scim:schemas:extension:CustomExtensionName:2":{"0:User":{"otherMails":"yz@ab,ef@op,mn@op,abc@br"}},"emails":[{"type":"work","value":"abc@cde"}],"schemas":["urn:ietf:params:scim:schemas:core:2.0:User","urn:ietf:params:scim:schemas:extension:CustomExtensionName:2"],"meta":{"resourceType":"User","location":"<sample_location>"}}}

I think the attribute and schema should be urn:ietf:params:scim:schemas:extension:CustomExtensionName:2.0:User

expected outbound-

{"statusCode":200,"statusMessage":"OK","body":{"id":"<sample_id>","userName":"<sample_userName>","name":{"familyName":"test1"},"urn:ietf:params:scim:schemas:extension:CustomExtensionName:2.0:User":{"otherMails":"yz@ab,ef@op,mn@op,abc@br"},"emails":[{"type":"work","value":"abc@cde"}],"schemas":["urn:ietf:params:scim:schemas:core:2.0:User","urn:ietf:params:scim:schemas:extension:CustomExtensionName:2.0:User"],"meta":{"resourceType":"User","location":"<sample_location>"}}}

I appreciate any help you can provide.

**Comment by niranjanvk** [comment]
I think we can fix the issue by moving 

line no- 2685- 2688  
if (mapTo.startsWith('urn:')) {
          mapTo = mapTo.replace('.', '##')
          noneCore = true
 }
inside if condition at line 2648

**Comment by jelhub** [comment]
Yes, this is a known Microsoft problem and the reason why I have suggested that you use an existing Entra ID target attribute e.g. the `locale` attribute

Ref #118 (May 23)

> There seems to be a bug in Entra ID related to self-defined target attributes, and as you mention, these attributes are not included in create user. Also, Entra seems to ignore content retrieved in these attributes resulting in Entra applying the same on every sync.

> You may take this problem with Microsoft.

> Workaround seems to be using an existing target attribute

**Comment by niranjanvk** [comment]
Hi @jelhub, thanks for the response!
I understand the issue with Entra but my concern is with the outbound response from Scimgateway (please check the attached sample outbound). I tried modifying the code as I have mentioned in the comment and look like entra stopped sending repetitive patch requests because the attribute and value of the outbound response match with the attribute and values present in Entra. 

I request you to check the outbound response part.

Thanks

**Comment by jelhub** [comment]
endpointMapper using CustomExtension now fixed in v4.5.5
Thanks

**Comment by niranjanvk** [comment]
Hi @jelhub, thanks for the update but I believe there is another issue in https://github.com/jelhub/scimgateway/blob/956f13dd7bef32175058c22e40e6cb77c088d3f4/lib/scimgateway.js#L2667C17-L2667C101

In the case of multi values, the values in the response string are in reverse order .

please note- type is array and inboundtype is string

**Comment by jelhub** [comment]
What plugin and endpoint are you using?

Reason for the "reverse order" logic is because of plugin ldap behaviour and was tested using Microsoft Active Directory multivalue attribute.

Are you in the same team as those reported #118?
I assume "reverse order" logic was working for them using plugin ldap.

**Comment by niranjanvk** [comment]
Yes, I am in the same team and he may not test the order of values in response.
When I am trying with your current code because of reverse order of values in string, while matching with source value, Entra is finding both different and sending a Patch request.

The expression I am using as source is  Join(",", Split([otherMails], ",")) and urn:ietf:params:scim:schemas:extension:CustomExtensionName:2.0:User:otherMails as target in Entra mapping.

**Comment by jelhub** [comment]
As mentioned, when using Microsoft Active Directory I had to use "reverse order" logic to get returned to Azure the same as what was sent from Azure.

On the first user lookup by Azure, there will probably be a multivalue order mismatch, and you then get a patch (modifyUser) requst from Azure. But after this patch, there should not be any order mismatch and you should not get any continuous patch on every sync cycle.

Do you get the same multivalue patch on every sync cycle?

**Comment by jelhub** [comment]
Also please provide the INFO log entry showing inbound and outbound information

**Comment by niranjanvk** [comment]
Its continuously sending the patch request and I am getting same multivalued patch on every sync cycle.


Please check the order of values in inbound and outbound

Inbound = {"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations":[{"op":"Replace","path":"urn:ietf:params:scim:schemas:extension:CustomExtensionName:2.0:User:otherMails","value":"ces_user4@dinnerplease3.com,ces_user4@dinnerplease2.com,ces_user4@dinnerplease.com"}]} Outbound = {"statusCode":200,"statusMessage":"OK","body":{"id":"<id>","userName":"<user_name>","name":{"familyName":"ces_user4_sn"},"urn:ietf:params:scim:schemas:extension:CustomExtensionName:2.0:User":{"otherMails":"ces_user4@dinnerplease.com,ces_user4@dinnerplease2.com,ces_user4@dinnerplease3.com"},"emails":[{"type":"work","value":"ces_user4@innerpeace.com"}],"schemas":["urn:ietf:params:scim:schemas:core:2.0:User","urn:ietf:params:scim:schemas:extension:CustomExtensionName:2.0:User"],"meta":{"resourceType":"User"}}}

**Comment by niranjanvk** [comment]
seems working. thanks
