### ISSUE TITLE
Cannot PUT /Users

### ISSUE THREAD

**Issue by bbaassssiiee** [jelhub/scimgateway#13]
My Identity provider wants to PUT all the Users and Groups in a batch. scimgateway does not seem to support PUT for this, only POST and PATCH. That will not work with their software (ADFS?)

I Tried the Loki plugin with scim 2.0 and this JSON

```
[
  {
    "externalId": "Donald_D",
    "userName": "Donald_D",
    "active": "true",
    "schemas": [
      "urn:ietf:params:scim:schemas:core:2.0:User",
      "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
    ]
  },
  {
    "externalId": "Huey_D",
    "userName": "Huey_D",
    "active": "true",
    "schemas": [
      "urn:ietf:params:scim:schemas:core:2.0:User",
      "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
    ]
  },
  {
    "externalId": "Dewey_D",
    "userName": "Dewey_D",
    "active": "true",
    "schemas": [
      "urn:ietf:params:scim:schemas:core:2.0:User",
      "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
    ]
  },
  {
    "externalId": "Louie_D",
    "userName": "Louie_D",
    "active": "true",
    "schemas": [
      "urn:ietf:params:scim:schemas:core:2.0:User",
      "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
    ]
  }
]
```

**Comment by bbaassssiiee** [comment]
> --2018-02-28 11:25:57--  http://localhost:8880/Users
> Resolving localhost... 127.0.0.1
> Connecting to localhost|127.0.0.1|:8880... connected.
> HTTP request sent, awaiting response... 401 Unauthorized
> Authentication selected: Basic realm=""
> Reusing existing connection to localhost:8880.
> HTTP request sent, awaiting response... 404 Not Found
> 2018-02-28 11:25:57 ERROR 404: Not Found.
>

**Comment by jelhub** [comment]
Hi,
You might be looking for the SCIM bulk operator functionality?
http://www.simplecloud.info/specs/draft-scim-api-01.html#bulk-resources
https://tools.ietf.org/html/rfc7644#section-3.7

Regards,
Jarle

**Comment by schiphol-wilbur** [comment]
INVALID, we PUT them in one by one.

```
#!/bin/sh -e

wget -q --method=PUT \
 --output-document=/dev/null \
 --header "Content-Type: application/json" \
 --http-user=scim_admin --http-password=change_it \
 --body-file=testdata/Donald.json http://localhost:8880/Users/Donald_D
```

**Comment by schiphol-wilbur** [comment]
Issue can be closed

**Comment by jelhub** [comment]
ScimGateway would pass body content to plugin code
Your plugin could then check for array content and parse this content.
For each user you could then emit a modifyUser or createUser having correct userName and attrObj content

In method scimgateway.on('createUser',...) or scimgateway.on('modifyUser',...)
you then do:
scimgateway.emit('modifyUser', baseEntity, userName, attrObj, function (err) {...}

Body sent to ScimGateway must be JSON:

{
  "values": [
    {
      "externalId": "Donald_D",
      "userName": "Donald_D",
      "active": "true",
      "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User",
        "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
      ]
    },
    {
      "externalId": "Huey_D",
      "userName": "Huey_D",
      "active": "true",
      "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User",
        "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
      ]
    },
    {
      "externalId": "Dewey_D",
      "userName": "Dewey_D",
      "active": "true",
      "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User",
        "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
      ]
    },
    {
      "externalId": "Louie_D",
      "userName": "Louie_D",
      "active": "true",
      "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User",
        "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
      ]
    }
  ]
}
