### ISSUE TITLE
Keycloak REST API plugin

### ISSUE THREAD

**Issue by allebone** [jelhub/scimgateway#130]
As Keycloak doesn’t natively support SCIM currently. Is there an example that might best fit a workflow where Entra SCIM informs SCIMGATEWAY with Keycloak as a downstream plugin target?

**Comment by jelhub** [comment]
You may use plugin-entra-id as a REST-template.

Start working on the getUsers method and maybe having getGroups method returning empty to skip group logic in the initial phase `return { Resources: [] }`

For getUsers, following must work:
```
http://localhost:8881/Users
http://localhost:8881/Users/<id>
Not used by Entra, but may be used by others:
http://localhost:8881/Users?filter=userName eq "bjensen"
```

Make sure getUsers works before adjusting other methods you might need like modifyUsers, createUsers, deleteUser, getGroups…
