### ISSUE TITLE
Can we change value of uid?

### ISSUE THREAD

**Issue by niranjanvk** [jelhub/scimgateway#132]
Hi,

we noticed the value of uid in ldap plugin is always same as userName, even if we are not mapping it in conf file.

Is there any particular reason of keeping this or according to our requirement we can change it? 

context- we were checking if we can map the value of objectid as uid.

Thanks

**Comment by jelhub** [comment]
Not sure I understand your question.

There are two important and mandatory SCIM attributes: id and userName (or externalId)

Default provided config example for Active Directory shows
```
      "user": {
        "dn": {
          "mapTo": "id",
          "type": "string"
        },
        "sAMAccountName": {
          "mapTo": "userName",
          "type": "string"
        },
```

In this case we link SCIM userName with endpoint/ldap sAMAccountName

You are free to link according to you needs. You might not be using Active Directory and do not have any sAMAccountName attribute.

So, the answer to this issue title "Can we change value of uid" is yes if you by uid mean what is linked to userName e.g. sAMAccountName as shown in example

But keep in mind that SCIM userName must be unique within your endpoint, using firstName/lastName is not an option, using employeenumber is probably OK.

**Comment by jelhub** [comment]
Maybe below config is what this issue is about?
The naming attribute that also will be set in DN when we create user/group?

Below shows that CN will be the naming attribute and for user it will be set to the value of SCIM userName

As stated in v4.5.8, we now have the flexibilty to choose which SCIM attribute to link to the naming attribute. In previoius version it was hardcoded to userName/displayName

```
  "namingAttribute": {
	"user": [
	  {
		"attribute": "CN",
		"mapTo": "userName"
	  }
	],
	"group": [
	  {
		"attribute": "CN",
		"mapTo": "displayName"
	  }
```

**Comment by niranjanvk** [comment]
Hi @jelhub ,
yes, the naming attribute has fixed the issue I was facing.

Thanks,
