### ISSUE TITLE
The attribute mapped to name is not being send in Get request response

### ISSUE THREAD

**Issue by niranjanvk** [jelhub/scimgateway#133]
https://github.com/jelhub/scimgateway/blob/184e22800430c7ebf672858a37e84801144ead66/lib/plugin-ldap.js#L212

Hi @jelhub, any specific reason for deleting the name from the user? I cannot map any attribute to the name in openldap because if I map it is not present in the GET request response.

Thanks,

**Comment by jelhub** [comment]
Seems to be a leftover.
Now fixed in v4.5.9
