### ISSUE TITLE
How to map memberof attribute using plugin-ldap

### ISSUE THREAD

**Issue by niranjanvk** [jelhub/scimgateway#134]
Hi @jelhub, 
I am not finding a way to sync memberof attribute from entra to scimgateway. If you have any idea on how to map memberof attribute in entra, kindly share with me or is ther any way in code to create a attribute memberof

Thanks,

**Comment by jelhub** [comment]
You have to set:
`scimgateway.scim.groupMemberOfUser = true`

And for plugin-ldap you have to mapTo `groups.value` with type array
Like default config using Active Directory memberOf 

```
map.user:
       "memberOf": {
          "mapTo": "groups.value",
          "type": "array"
        },
```
E.g. default plugin-loki using multivalue group attribute (this plugin does not check if group does exist when using groupMemberOfUser):

```
PATCH http://localhost:8880/Users/bjensen

{
    "schemas": ["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
    "Operations": [{
            "op": "Add",
            "path": "groups",
            "value": [{
                    "value": "ID-Group1"
                }, {
                    "value": "ID-Group2"
                }
            ]
        }
    ]
}
```

So, Entra ID must send the memberOf content as SCIM groups multivalue

**Comment by niranjanvk** [comment]
I have already done the scimgateway part in plugin-ldap.json. I not finding a source attribute for memberof in Entra User or Group mapping.

**Comment by jelhub** [comment]
Normally users are member of groups and not groups member of users (memberOf)

In Active Directory we do have memberOf on the user object, but this is virtual attribute having logic behind-the-scenes.

You probably have to use some expression logic in the Entra ID provisioning mapping.

Also keep in mind what mentioned in #118:
There seems to be a bug in Entra ID related to self-defined target attributes, these attributes are not included in create user. Also, Entra seems to ignore content retrieved in these attributes resulting in Entra applying the same on every sync.
