### ISSUE TITLE
Modify when type is array is not working

### ISSUE THREAD

**Issue by niranjanvk** [jelhub/scimgateway#136]
Hi @jelhub,

When I try to modify an attribute with type array and inbound type string and that attribute does not exist already it fails. The reason for failure is that the attribute value is deleted before adding in the case of Array and it through error 'No such attribute'.

https://github.com/jelhub/scimgateway/blob/a8c871fd97a70cd9ece5cf3818ddbfe3f8c11c78/lib/plugin-ldap.js#L1390

using plugin-ldap with openldap and entra id.

Thanks,
Vipin

**Comment by jelhub** [comment]
Seems to be a difference using OpenLDAP or not

Anyhow, the deletion logic have already been changed with regards to #135 - Q3
So, issue will be fixed using next release v4.5.11 (not yet published)
