### ISSUE TITLE
If the value of attribute mapped to naming attribute is modified in Entra, its not being updated in scimgateway

### ISSUE THREAD

**Issue by niranjanvk** [jelhub/scimgateway#137]
Hi @jelhub 

If value of attribute mapped in namingAttribute is modified from source (Entra) and then a PATCH request is sent the value is not updated for key in namingAttribute in scimgateway.

https://github.com/jelhub/scimgateway/blob/c09516c07786f6e9fa21cbd51c6e612a4723ac47/config/plugin-ldap.json#L151

thanks,

**Comment by jelhub** [comment]
Now fixed in v4.5.12

[Improved]

- plugin-ldap, new configuration { allowModifyDN: true } allows DN being changed based on modified mapping or namingAttribute
