### ISSUE TITLE
If dn contains non-ascii characters like chinese or Hindi characters the GET group is failing

### ISSUE THREAD

**Issue by niranjanvk** [jelhub/scimgateway#138]
Hi @jelhub,

https://github.com/jelhub/scimgateway/blob/b3294172e6d566bc78f17f782c68cbd1f235402f/lib/plugin-ldap.ts#L1453

what is the purpose of this function? can we remove it or fix the issue quickly?

thanks,
Vipin

**Comment by jelhub** [comment]
Code converts any dn hex encoded characters to readable format

Will removing this code fix your problem?

Please show some examples of Hindi dn that does not work.

I have tested "cn=Tअhindi", but could not see any problems.
Assume you are using OpenLDAP and configuration `"isOpenLdap": true`

**Comment by niranjanvk** [comment]
That specific replace function is the issue and if I comment the function, everything work good.

**Comment by niranjanvk** [comment]
Thanks for the quick response and fix!
