### ISSUE TITLE
filter doesn't support customization

### ISSUE THREAD

**Issue by GregLabelle** [jelhub/scimgateway#15]
In developing a custom plugin, I would like to fully support the filtering as specified in the SCIM standard.  However, it appears that the code only allows for displayname filtering .. and returns a 404 on any filter that doesn't include that attribute.

Is it possible to bypass the filter check, and pass the entirety of the filter querystring onto the plugin for manual parsing?

**Comment by jelhub** [comment]
v2.1.2 now includes option for replacing mandatory userName/displayName attribute by configuring customUniqueAttrMapping
	  
Example:

    "scim": {
      "version": "1.1",
      "customSchema": null,
      "customUniqueAttrMapping" : {
        "userName" : "userPrincipalName",
        "displayName": "externalId"
      }

Regards,
Jarle

**Comment by jelhub** [comment]
Using `"displayName": "externalId"` was not the best example

"externalId" is included and handled by default:
userName/externalId = default User unique attribute
displayName/externalId = default Group unique attribute

Jarle
