### ISSUE TITLE
compound operations in Patch result in an error

### ISSUE THREAD

**Issue by GregLabelle** [jelhub/scimgateway#16]
When posting a patch to replace all group memberships per the following:

`{
       	"op":"remove",
       	"path": "members"
       },
       {
       	"op":"add",
       	"path":"members",
       	"value": {
       		"value": "Group1"
       	}
}`

The gateway can process the filters individually, but not together.  Per the SCIM standard, the operations should be accepted, and processed sequentially based on the input.  As this is part of a custom plugin, perhaps the easiest way to deal with this is to allow bypassing the built in parse of the operations, and pass the entire body to the handler in the plugin.  This could be based on a flag in the plugin configuration for ease of use.

**Comment by jelhub** [comment]
Testing having value as array gives correct result e.g:

`{ "op":"remove", "path": "members" }, { "op":"add", "path":"members", "value": [{ "value": "Group1" }] }`

Anyhow, none array is now supported in v2.1.2

Regards,
Jarle
