### ISSUE TITLE
Security vunerability - SOAP / EJS

### ISSUE THREAD

**Issue by visualjeff** [jelhub/scimgateway#2]
I mean vulnerability.  Sorry.

SOAP dependency is outdated and **insecure**.  See attachment below (a screen shot).  Need to make we pull in a newer version of SOAP that is using a newer version of ejs.  ejs is the source of the security issue.  BTW, You'll notice SOAP's master branch has been updated.

![screen shot 2017-03-03 at 1 55 21 pm](https://cloud.githubusercontent.com/assets/3446106/23570627/e30e51d8-0019-11e7-842b-a11ea3459b74.png)

If you like I could update your project.json and submit a pull request?

Jeff
PS. I'm a co-worker of C. Watson.

PS. More details about the vulnerability can be found here:  [https://snyk.io/vuln/npm:ejs:20161128](https://snyk.io/vuln/npm:ejs:20161128)

**Comment by jelhub** [comment]
Thank you for sharing this information.
Next release will include dependency updates.

Regards,
Jarle

**Comment by jelhub** [comment]
Release 0.4.0 includes latest versions of all dependencies
Thanks
