### ISSUE TITLE
mssql does not return data

### ISSUE THREAD

**Issue by RuneHL** [jelhub/scimgateway#20]
Hi
The mssql plugin does not return data in my installation. 
It appears that the exploreUsers method returns an empty data set before the query is run. If I add logging statements in the Tedious Request callback the data is returned from SQL Server.
I cannot see how to resolve the synchronization with Tedious. Hope you can help.

**Comment by jelhub** [comment]
Now fixed in v2.1.8
Thanks, Jarle

**Comment by RuneHL** [comment]
Thank you for the fix, tested and OK :-)
