### ISSUE TITLE
Can we change path for log file ?

### ISSUE THREAD

**Issue by mohitzim** [jelhub/scimgateway#24]
Hi jelhub

By default, scimgateway creates log file on **logs/plugin-loki.log** path. Can we provide custom path for log-file ?

Regards

**Comment by jelhub** [comment]
Hi,

No, but can instead redirect the console logging (stdout/stderr) to a file

On a windows box, startup will then be something like:
`node index.js > c:\temp\my-custom-logfile.log 2>&1`

Regards,
Jarle

**Comment by mohitzim** [comment]
Thanks jelhub. This works.
