### ISSUE TITLE
Cannot access body of SCIM 2.0 PUT requests

### ISSUE THREAD

**Issue by nipund** [jelhub/scimgateway#25]
When the PUT body is passed to the modifyUser function, it is always an empty object because of this line:

https://github.com/jelhub/scimgateway/blob/f02de6e287b85c8c4d1153066efeb9cfb265284f/lib/scimgateway.js#L1655

**Comment by jelhub** [comment]
Now fixed in v3.0.2

Thanks,
Jarle
