### ISSUE TITLE
GET /Users endpoint not compatible with Okta

### ISSUE THREAD

**Issue by nipund** [jelhub/scimgateway#26]
When registering a new app in Okta with SCIM 2.0, it makes a GET call to /Users with `startIndex` and `count` keys but no `attributes` key. This will always fail in the current version of scimgateway.

https://github.com/jelhub/scimgateway/blob/1a9501c16d3ca084671e53a772c2b36575a71e4a/lib/scimgateway.js#L708

Relvant part of Okta protocol reference: https://developer.okta.com/docs/reference/scim/scim-20/#retrieving-users

**Comment by jelhub** [comment]
Now fixed in v3.0.3

Thanks,
Jarle
