### ISSUE TITLE
Security vulnerability - SAML / MOMENT / EJS & NODE-FORGE

### ISSUE THREAD

**Issue by visualjeff** [jelhub/scimgateway#3]
Couple of dependencies with SAML package need to be updated to resolve these **security issues**.  See attachment below (a screen shot).

![screen shot 2017-03-03 at 2 07 24 pm](https://cloud.githubusercontent.com/assets/3446106/23571246/fdf8a4fa-001c-11e7-8395-a40f46e1d128.png)

Jeff

**Comment by jelhub** [comment]
Thank you for sharing this information.
Next release will include dependency updates.

Regards,
Jarle

**Comment by jelhub** [comment]
This is a saml package issue.
You may update saml package dependencies manually or contact owner.
Thanks

**Comment by jelhub** [comment]
FYI, scimgateway nor example plugins use SAML package.
SAML is included because I have made other plugins that use this package. I have also included SAML examples in forwardinc that is comment out.
