### ISSUE TITLE
ldap provisioning

### ISSUE THREAD

**Issue by bvduijn** [jelhub/scimgateway#30]
Hi Jelhub,

Interesting project you have here! 
I was wondering. Would it also be possible to create an LDAP provisioner?

I've found https://www.npmjs.com/package/ldapjs and I guess it should be possible but I lack knowledge of NodeJs

**Comment by jelhub** [comment]
Hi,
Yes, you can use ldapjs.
I have been using ldapjs for Microsoft Active Directory provisioning.

Regards,
Jarle

**Comment by bvduijn** [comment]
Hi Jarle,

Any chance you could share the code? Or are you using it outside of the scimgateway ?

Regards,
Bert

**Comment by jelhub** [comment]
Hi,

It's customized and not for a general template.

Main reason for not including a directory example plugin, is that all IdP's supports directory endpoints and therefore it have not been on the priority list. But of course there are use cases where a directory plugin is needed e.g. Azure to on-premise AD or other directories. Or when not using IdP, but instead using your own API's towards SCIM Gateway.

Regards,
Jarle

**Comment by jelhub** [comment]
FYI,
LDAP plugin now included in v3.1.0

Regards,
Jarle
