### ISSUE TITLE
Can I use multiple plugins?

### ISSUE THREAD

**Issue by sachinsh76** [jelhub/scimgateway#31]
- Looking at the current implementation, every plugin needs a config file that describes the standard ```scimgateway``` configuration.
- If I want to use multiple plugins in the same gateway application, how can I do that?
- It will contain scimgateway config. for each plugin which can create problems.

**Comment by jelhub** [comment]
Yes, you can run as many plugins you want in the same gateway (using unique port number)

Take a look at default index.js, you may uncomment all plugins from startup and they will all be running.

Travis tests shows test result for 3 plugins running in same gateway: https://travis-ci.org/github/jelhub/scimgateway

Regards,
Jarle

**Comment by sachinsh76** [comment]
Wow, that's incredible. Helps a lot 👍
