### ISSUE TITLE
Returning wrong schema for modifyGroup PATCH request

### ISSUE THREAD

**Issue by davefend-okta** [jelhub/scimgateway#33]
PATCH requests come in with urn:ietf:params:scim:api:messages:2.0:PatchOp for the schema value.   The router.patch method is simply echoing back the schema that is sent from the server.  It needs to be sure to return ['urn:ietf:params:scim:schemas:core:2.0:Group'] for the schema.

I inserted the following:
_ctx.body = jsonBody // using original body instead of retrieving actual data_
        **// The schema comes in ["urn:ietf:params:scim:api:messages:2.0:PatchOp"].  That needs to be converted to 
        // ['urn:ietf:params:scim:schemas:core:2.0:Group'] for the response.  Line below was inserted
        ctx.body.schemas=['urn:ietf:params:scim:schemas:core:2.0:Group']**

This updates the schema to ensure the correct value is returned.  Servers validating the schema value will fail until this is done

**Comment by jelhub** [comment]
Hi,
Yes, I'm aware of this problem.
This and other things are fixed in v3.2.1 that will soon be available.
Actually PATCH should return 200 with no content
Returning 204 with content if PATCH includes query `attributes` or `excludedAttributes`

Thanks,
Jarle

**Comment by jelhub** [comment]
correction:
204 with no content
200 with content

**Comment by jelhub** [comment]
v3.2.1 now available
You may verify if problem solved

**Comment by jelhub** [comment]
FYI,
User attribute `groups` is not handled correctly by plugin-loki (default when running SCIM Gateway "as is")
If your IdP retrieves group membership based on User-groups attribute and not by Group-members.value, it will not work as expected

This will be fixed in v3.2.2

Regards,
Jarle

**Comment by jelhub** [comment]
v3.2.2 have now been published.
