### ISSUE TITLE
Updated tedious package breaks mssql sample. 

### ISSUE THREAD

**Issue by demesg** [jelhub/scimgateway#34]
Hi 
Started a fresh install and found that mssql does not work. Tedious is not connecting to server at all. 
I guess it has something to do with the new way to make a connection that was introduced in v10.
When using 9.2.1 it works. 

https://github.com/tediousjs/tedious/releases
10.0.0 (2021-01-13)
BREAKING CHANGES
Creating a new Connection instance will no longer establish a connection to the server automatically. Please use the new connect helper function or call the .connect method on the newly created Connection object instead.

best regards 
Magnus

**Comment by jelhub** [comment]
Now fixed in v3.2.3
Thanks, Jarle
