### ISSUE TITLE
Using auth.bearerJwt option doesn't work if using public key

### ISSUE THREAD

**Issue by rovania2000** [jelhub/scimgateway#37]
Tried using auth.bearerJwt  option but it fails as the code is initializing only if secret is specified. Once secret is specified the token validation uses only the secret. Was able to get it working after fixing the code related to auth.bearerJwt initializatin.

**Comment by jelhub** [comment]
Issue fixed in v3.2.6

Thanks,
Jarle

**Comment by rovania2000** [comment]
Thanks Jarle!
