### ISSUE TITLE
How to get cleartext bearer token in functions?

### ISSUE THREAD

**Issue by ThomasPCG** [jelhub/scimgateway#39]
When modifying users, I would like to keep track of who did the action based on the bearer token used. However, I can't seem to find a method or parameter which will return the bearer token for me to reference the respective user.

Is there a way to do so?

![image](https://user-images.githubusercontent.com/25073827/122016657-d1784800-cdf3-11eb-8bd1-03cd4bbdfed1.png)

**Comment by jelhub** [comment]
SCIM Gateway do not pass bearer token to plugins.

In this case you need to have your own modified version of scimgateway.js that pass needed bearer information to plugin

scimgateway.js:
`await this[handle.deleteMethod](ctx.params.baseEntity, id, bearer)`

plugin.js:
`scimgateway.deleteUser = async (baseEntity, id, bearer) => {`

Regards,
Jarle
