### ISSUE TITLE
MongoDB or MySQL plugins

### ISSUE THREAD

**Issue by jmaferreira** [jelhub/scimgateway#42]
Hi,

Do you know of anyone who has developed a plugin for MongoDB or MySQL? I can't seem to find any references anywhere.

If you develop that ourselves, would you like to add it to your repository?

Cheers.

**Comment by jelhub** [comment]
Hi,

Answer is no.

But plugin-loki and plugin-mssql should be almost the same.
You could for example replace loki with mongodb package and tedious with mysql package.
Then some minor changes regarding connections and requests.

Regards Jarle

**Comment by jmaferreira** [comment]
Dear @jelhub,

Thanks. We will probably implement one of those two and quite possibly add more operators to the REST API such as "gte".
