### ISSUE TITLE
add a property to disable activities of postinstall script

### ISSUE THREAD

**Issue by rotty3000** [jelhub/scimgateway#49]
Using the ability for `.npmrc` properties to be available via `process.env`, add a check for a property which can disable postinstall script to simplify keeping up to date.

PR on it's way...

## Why is this useful
this is what I added to the README:

When maintaining a set of modifications it useful to disable the postinstall operations to keep your changes intact by setting the property `scimgateway_postinstall_skip = true` in `.npmrc`.

## What problem it solves
to not have (allows me to delete) plugins and integrations with databases I don’t use

**Comment by rotty3000** [comment]
To be even more clear this is an improvement so that in the future if we update scimgateway dependency it doesn't re-add all those files, which means I can safely delete all the ones we don't use. :)

**Comment by jelhub** [comment]
I will look into this in the next update

Thanks,
Jarle

**Comment by jelhub** [comment]
Maybe better to skip postinstall script if config and lib directory exists
Jarle

**Comment by rotty3000** [comment]
That is one option, there is also ability to send command line parameters to npm `scripts`.
