### ISSUE TITLE
add support for interpolation of raw text secrets files

### ISSUE THREAD

**Issue by rotty3000** [jelhub/scimgateway#51]
## Why is this requested
We store secure values in a secretes engine as individually managed units. Assembling all those values into files at deployment time is not a best practice.

## The proposed solution
The predominant way to provide these secretes is by mounting them directly in the file system as individual files with raw text values. I'd like to propose to extend the `process.env.|file.` model adding `process.text.` which would allow a file to be read as just a (`UTF-8`) string.

**Comment by jelhub** [comment]
Very good, I will include this in the next update

Thanks,
Jarle
