### ISSUE TITLE
primary email not set error while trying to sync users

### ISSUE THREAD

**Issue by shahidv3** [jelhub/scimgateway#58]
Hi @jelhub 

Using LDAP plugin - we can retrieve the AD users/groups details successfully. And We can register the SCIM GW application on Oracle cloud. However during users sync noticed that it is failing with  error like "Primary email must be set"

When we invoke  get /Users endpoint from browser - we see email details of type and value but no 'primary' information . 
I have noticed that in plugin-ldap.js we need to expose the emails.primary attribute in /Users endpoint.

following are attributes mapping from cloud to application
$(account.primaryEmail) --> emails[primary eq true and type eq "work"].value
Please let me know your thoughts on this one. 

many thanks

**Comment by shahidv3** [comment]
Hi @jelhub 

Thanks for the response.

Yes OCI requires primary to be set on the email address.
I'm calling plugin-ldap to read users/groups from on-prem AD ( users/groups are already created on this AD) and then sync to OCI IDCS. Hence not using createUser method

 I assume I can update the getUsers method to show email as type of 'work' with value in addition primary boolean value as 'true' as shown in below.

"emails": [
    {
      "value": "bjensen@example.com",
      "type": "work",
      "primary": true
    }

Please let me know your thoughts.

many thanks, shahid

**Comment by jelhub** [comment]
plugin-ldap do not hardcode any primary on email retrieved.
You either have to update plugin-ldap or the sync logic to include the primary

Jarle
