### ISSUE TITLE
custom attribution addition

### ISSUE THREAD

**Issue by shahidv3** [jelhub/scimgateway#62]
hi @jelhub 

Thanks for SCIM GW. I have synced users from on-prem AD to Oracle IDCS
while verifying the sync user information - "Federated" option is disabled in IDCS

Inorder to enable this - I'm wondering if we need to create the following custom attribute on on-prem AD by updating the schema or just map custom attribute in SCIM GW.

- Mapping type: Constant
- Constant value: true
- Target attribute: urn:ietf:params:scim:schemas:oracle:idcs:extension:user:User:isFederatedUser

please share your thoughts
https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/oracle-cloud-infrastructure-console-provisioning-tutorial

thanks

**Comment by jelhub** [comment]
Hi,

You probably need to include `isFederatedUser` in the POST/PATCH sent to Oracle

Examples:

Create User:
```
{
  "schemas": ["urn:ietf:params:scim:schemas:core:2.0:User",
  "urn:ietf:params:scim:schemas:oracle:idcs:extension:user:User"],
  ...,
  "urn:ietf:params:scim:schemas:oracle:idcs:extension:user:User": {
    "isFederatedUser": true
  }
}
```

Modify User:

```
{
  "Operations": [
    ...,
    {
      "op": "Replace",
      "path": "urn:ietf:params:scim:schemas:oracle:idcs:extension:user:User:isFederatedUser",
      "value": true
    }
  ],
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ]
}
```

Regards
Jarle

**Comment by shahidv3** [comment]
thanks @jelhub for the quick reply.

I'm not creating or modifying any users - but using plugin-ldap.js to list on-prem AD users and groups.


thanks , sahid

**Comment by jelhub** [comment]
I assume you retrieves users from AD using plugin-ldap, but you also need some logic for syncing (update/modify) these users in Oracle. So, in this sync logic you need to include what mentioned.

**Comment by shahidv3** [comment]
thanks @jelhub 

is this the right approach

` const method = 'modify'
  let base
  if (config.useSID_id) {
    const sid = convertStringToSid(id)
    if (!sid) throw new Error(`${action} error: id=${id} - attribute having a none valid SID string`)
    base = `<SID=${sid}>`
  } else if (config.useGUID_id) {
    const guid = Buffer.from(id, 'base64').toString('hex')
    base = `<GUID=${guid}>`
  } else base = id // dn
  const ldapOptions = {
    //operation: 'replace',
    "Operations": [
      {
        "op": "Replace",
        "path": "urn:ietf:params:scim:schemas:oracle:idcs:extension:user:User:isFederatedUser",
        "value": true
      }
    ],
    "schemas": [
      "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    modification: endpointObj
  }`

**Comment by jelhub** [comment]
You are referring to plugin-ldap code which use directory, in this case AD.

Why modify a user in AD when problem is related to Oracle specific attribute `isFederatedUser` on a user in OCI?
I assume you can fix problem manually by using Oracle Admin UI and enable federation (isFederatedUser) on users having this problem?
```
1) AD ==LDAP==> read users (plugin-ldap)
2) (plugin-scim?) ==SCIM==> OCI create/modify users (sync)
```
Could you please explain #2, how do you sync (create/modify) users in OCI?
This part probably needs to include the `isFederatedUser` attribute.

Jarle

**Comment by shahidv3** [comment]
Thanks @jelhub 

Yes , I can fix the problem by manually updating the "federation" to enable in UI.
However it will be cumbersome activity if the number of users are more and moreover it will be overhead.

or I can make use of bulk rest api from Oracle to update isFederatedUser.

Regarding how I'm syncing the users in OCI . OCI support SCIM client registration which will  read SCIM /users and /groups endpoint . Once the connectivity is done - the users can be synced succesfully.

thanks , sahid

**Comment by jelhub** [comment]
OK, so OIC retrieves users from SCIM Gateway using Authoritative Sync

In your OIC application:
`Provisioning - Attribute Mapping - Application to Identity Cloud`

Add Row:
SCIM Gateway Account: `$(account.isFederated)` Maps to: `Federated`

In plugin-ldap, the getUsers() needs to include isFederated attribute and it should be hardcoded to true.

Change:
https://github.com/jelhub/scimgateway/blob/master/lib/plugin-ldap.js#L254

To:
```
// return scimgateway.endpointMapper('inbound', user, config.map.user)[0] // endpoint attribute naming => SCIM
const usr = scimgateway.endpointMapper('inbound', user, config.map.user)[0] // endpoint attribute naming => SCIM
usr.isFederated = true // OIC Federated
return usr
```

Jarle

**Comment by shahidv3** [comment]
hi @jelhub 

Thank you !!

Worked like a charm !!

I have added the following in plugin-ldap.json

```
"fed": {
          "mapTo": "isFederated",
          "type": "string"
        }
```

added the following in plugin-ldap.js

```
if (user.fed === undefined) {
        const fed = user.fed
        user.fed = true
       
    }
```

Added this  Row in OCI 
```
SCIM Gateway Account: $(account.active) Maps to: Federated
```
I tried adding $(account.isFederated) - it was throwing invalid expression. Followed the workaround to update it as $(account.active)

I see now the sync user as "Federated as True"

Many thanks,
Shahid

**Comment by jelhub** [comment]
Yes, using `$(account.active) Maps to Federated` will work. This is probably the easies way and do not require any changes in the plugin-ldap

The "fed" and user.fed logic you mentioned do not have any mission.

isFedereated is not a valid SCIM User attribute according to User schema.
OCI probably validates according to this schema and therefore throwed an exception.

I'm glad it worked out

Jarle
