### ISSUE TITLE
support for multiple DN  in plugin ldap configuration

### ISSUE THREAD

**Issue by shahidv3** [jelhub/scimgateway#64]
hi @jelhub 

Can we enable support for multiple DNs which has "(" and "&" to restrict the scope of AD

-  (&(objectclass=group)(cn="role-xyz"))
-  (memberOf=CN=role-xyz,OU=Groups,OU=xxx,DC=xx,DC=xxx,DC=xxx)

many thanks

**Comment by jelhub** [comment]
### v4.1.1  
[Added] 

- plugin-ldap support userFilter/groupFilter configuration for restricting scope  

    Configuration example:  

        {
          ...
          "userFilter": "(memberOf=CN=grp1,OU=Groups,DC=test,DC=com)(!(memberOf=CN=Domain Admins,CN=Users,DC=test,DC=com))",
          "groupFilter": "(!(cn=grp2))",
          ...
        }
