### ISSUE TITLE
Okta + Auth0

### ISSUE THREAD

**Issue by oryagel** [jelhub/scimgateway#66]
Hi,
I would like to use Okta and Auth0 such that the input is Okta (SCIM 2.0) and the output is Auth0.
I assume that Okta is compatible with scimgateway.
Is there a plugin in the work for Auth0? Assuming Auth0 is extremely popular, I was hoping there is already a plugin available.

Thanks

**Comment by jelhub** [comment]
Hi,
Gateway is SCIM 1.1 and 2.0 compliant, so Okta using 2.0 will be fine.
Sorry, but there are no Auth0 plugin that I'm aware of neither in the work.

Regards,
Jarle

**Comment by oryagel** [comment]
Got it.
Thanks!
