### ISSUE TITLE
Maximum payload size that the body-parser accepts is 1MB

### ISSUE THREAD

**Issue by SamMurphyDev** [jelhub/scimgateway#69]
The body parser is set to use the default json limit of 1mb for incoming payloads. There are cases which large groups that you could exceed that size.

https://github.com/jelhub/scimgateway/blob/master/lib/scimgateway.js#L578-L582

Adding in the `jsonLimit` limit to a higher amount or a configurable amount would be useful.

**Comment by jelhub** [comment]
Hi,
Thank you for your contribution.
Could you please do some small modification in pull request

Change from:
```
  "scimgateway": {
    ...
    "payloadSize": "1mb",
    ...
```
	
to:
```
  "scimgateway": {
    ...
    "payloadSize": null,
    ...
```	

Change from:
```
  jsonLimit: config.payloadSize !== undefined ? config.payloadSize : '1mb',
```

to:
```
  jsonLimit: (!config.payloadSize) ? undefined : config.payloadSize // default '1mb'
```

I will update readme accordingly

Thanks,
Jarle

**Comment by jelhub** [comment]
Thank you
