### ISSUE TITLE
installation on windows fails

### ISSUE THREAD

**Issue by belaie** [jelhub/scimgateway#74]
\Code\my-scimgateway>npm install scimgateway
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/msal-node@1.14.5',
npm WARN EBADENGINE   required: { node: '10 || 12 || 14 || 16 || 18' },
npm WARN EBADENGINE   current: { node: 'v19.2.0', npm: '8.19.3' }
npm WARN EBADENGINE }

up to date, audited 352 packages in 4s

52 packages are looking for funding
  run `npm fund` for details

5 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

**Comment by jelhub** [comment]
Hi,
You may ignore these warnings.

Module dependency `@azure/msal-node` have several hardcoded node versions as "suggested" requirements
When your Node.js version is >= 10, it should be fine for this module

Latest Node.js LTS version (supported) is v18.12.1 and you seem to be running v19.2.0

If you downgrade to latest LTS, warnings will be gone.

When it comes to severity vulnerabilities, it’s a never-ending story even though regular dependencies bumps

Regards,
Jarle
