### ISSUE TITLE
Sending token to backend

### ISSUE THREAD

**Issue by osbornk** [jelhub/scimgateway#75]
Our IDP will be sending a token to SCIM Gateway. In the handlers (createUser, updateUser, etc.) we want access to this token since it will then be used to communicate with our back end.

But the handler API is
```
scimgateway.createUser = async (baseEntity, userObj)
``` 

instead of
```
scimgateway.createUser = async (ctx, userObj)
```

Is there any other way of accessing the token of the original request to SCIM Gateway?

**Comment by jelhub** [comment]
Hi,

Currently there are no way to pass header information to plugin.

ctx should not be passed to plugin.

I will look into this issue and come back to you.

Regards,
Jarle

**Comment by osbornk** [comment]
Is there a particular reason ctx should not be passed to the plugin? We did this in our forked repo and it works, but now we want to get our changes back into your repo. I can submit a PR, but want to make sure it is consistent and flexible enough for other users.

One option I thought of is creating a `createApiClient(ctx)` handler that could create some sort of object that could then be passed back to `createUser`, `getUser`, etc. One downside would be that you could not have any logic that is specific to a particular handler. And that would be fine in my case.

**Comment by jelhub** [comment]
It's about component segregation of duties.
Passing ctx as reference is not good, but a copy of what is needed could be an option.

I assume header information is what you need.
Is it OK to exclude Auth tokens used by SCIM Gateway or do you needed these as well?

**Comment by osbornk** [comment]
Yes. Just the headers is what I need. And no, I don't need the SCIM Gateway auth tokens. I am actually working on a PR that I should have working shortly. Once I have it working please take a look and tell me what you think.

**Comment by osbornk** [comment]
Please take a look at https://github.com/jelhub/scimgateway/pull/77.

**Comment by jelhub** [comment]
It seems you are passing the same auth token that is used and known for scimgateway:
`ctx.state.authToken = authToken`

There are no new headers/tokens passed.

Auth tokens known for scimgateway can also be known for plugin.

**plugin-code:**
```
  let config = require(configFile).endpoint // this one is the original - pointing to the endpoint config managed by plugin
  let configScimgateway = require(configFile).scimgateway // this one is new - pointing to what is supposed to be managed by scimgateway

  // decrypt token config
  if (Array.isArray(configScimgateway.auth.bearerToken)) {
    const arr = configScimgateway.auth.bearerToken
    for (let i = 0; i < arr.length; i++) {
      if (arr[i].token) {
        try {
          arr[i].token = scimgateway.getPassword(`scimgateway.auth.bearerToken[${i}].token`, configFile)
        } catch (err) {
          scimgateway.logger.error(`${gwName}[${pluginName}] getPassword error: ${err.message}`)
          throw err
        }
      }
    }
  }

  // now we have token(s) e.g. configScimgateway.auth.bearerToken[0].token
```

**Comment by jelhub** [comment]
OK, I now understand the use case.

I will reject current pull request, do some changes and come back to you probably within a week.

1. authentication/allowing passthrough will be a request to plugin that needs to accept
2. then passing a copy of ctx only including ctx.request.header to plugin (not limiting to bearer auth token)

**Comment by osbornk** [comment]
Sounds good. I have a good test application with an internal test suite, so I can easily validate whether it works.

**Comment by jelhub** [comment]
Auth PassThrough now included in v.4.1.15

**Comment by osbornk** [comment]
Thanks. This looks like it should work just fine. I will update my code tomorrow to test it out.

**Comment by osbornk** [comment]
Everything looks good. Thanks.
