### ISSUE TITLE
SCIM default REST and SOAP endpoints

### ISSUE THREAD

**Issue by edgars** [jelhub/scimgateway#80]
Hi there,

Would be possible to show de scim schemas and wsdls ?

Besides, is there a way to present those via some URI?

**Comment by jelhub** [comment]
Just adding that scimgateway does not care about attributes used as long as mandatory attributes like id, userName, displayName are included where needed.

Attributes are handled by your own pluging and you have to decide what attributes to be used.

Some IdP's request schemas and some also use this schema for allowing attributes used towards scimgateway.

**Comment by edgars** [comment]
Thanks
