### ISSUE TITLE
Using SCIM Plugin for invoke one or more plugins

### ISSUE THREAD

**Issue by edgars** [jelhub/scimgateway#81]
Hi there,

Seems that scim-plugin.js is a proxy/façade for the other scim extensions, am I right? 

If it is the goal for scim-plugin.js how to add more than one endpoint as the requests destionation?

Cheers

Edgar

**Comment by jelhub** [comment]
Hi,

Plugins preferred way of implementing multi tenant or multi endpoint is using baseEntity

Please search in the documentation for `baseEntity`

Regards,
Jarle
