### ISSUE TITLE
Provide sample on how to pass token to backend

### ISSUE THREAD

**Issue by shiraze** [jelhub/scimgateway#90]
Following on from #75 it would be helpful if sample code showed how this could be done.

**Comment by jelhub** [comment]
Hi,

If you want to use the "as-is" PassThrough in plugin-scim, you may:
replace
  https://github.com/jelhub/scimgateway/blob/master/lib/plugin-scim.js#L660
with
  `options.headers.Authorization = ctx.request.header.authorization`

Regards,
Jarle

**Comment by jelhub** [comment]
v4.2.4 now includes Auth PassThrough support for provided plugins
