### ISSUE TITLE
Azure User Provisioning

### ISSUE THREAD

**Issue by Dhinesh1507** [jelhub/scimgateway#98]
Hi,

I am new to this SCIM and I am not a developer too.

I just read the guide, but I didn't get it. My requirement is to retrieve users from Azure AD whenever a user is created in Azure and send the user data to an external API. Which plugin should I use for this use case? 

Could you please assist me with this?

Thanks,
Dhinesh

**Comment by jelhub** [comment]
Hi,
Read: https://github.com/jelhub/scimgateway#azure-active-directory-as-idp-using-scim-gateway

You should start using default plugin-loki to become familiar with AAD as IdP and user provisioning.

Then you could adjust AAD provisioning and also adjust some of the existing plugins for your API.

Note, AAD provisioning will try to lookup user at endpoint. If not found, it will create user. Also note that plugin-loki is default "in-memory". Users created do not exist after restart.

Regards,
Jarle

**Comment by Dhinesh1507** [comment]
Hi Jarle,

Thanks for the suggestion. I am successfully able to provision with default plugin-Loki with Azure AD.

I need to send custom SCIM attributes from SCIM to Azure, map these attributes in Azure, and retrieve the data only for the attributes that have been mapped with Azure attributes.

I have tried all the possibilities from the guide, but I am unable to define the attributes and see them in Azure. Can you please help me define the custom attributes?

Thanks,
Dhinesh

**Comment by jelhub** [comment]
For provisioning to AAD you need to look at:
https://github.com/jelhub/scimgateway#azure-active-directory-provisioning

You might change scim.version from "1.1" to "2.0" here:
https://github.com/jelhub/scimgateway/blob/master/config/plugin-azure-ad.json#L7

SCIM to AAD attribute mapping can be configured here:
https://github.com/jelhub/scimgateway/blob/master/config/plugin-azure-ad.json#L111-L271

For starting plugin-azure-ad you have to uncomment in index.js
